<?php

/**
 * @file
 * Contains my_yamlform_element.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_yamlform_element_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_yamlform_element module.
    case 'help.page.my_yamlform_element':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
